# Generated by Django 3.2.9 on 2021-11-23 12:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kategori adını belirleyin.', max_length=500, null=True, unique=True, verbose_name='Kategori Adı')),
                ('description', models.CharField(help_text='Kategori hakkında kısa açıklama belirtin.', max_length=500, null=True, verbose_name='Açıklama')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('icon', models.CharField(help_text='Icon', max_length=500, verbose_name='Icon')),
                ('start_time', models.DateTimeField(null=True)),
                ('modefied_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='please write title', max_length=500, null=True, unique=True, verbose_name='title')),
                ('tags', models.CharField(help_text='sperate with comma (,)', max_length=500, null=True, verbose_name='Keywords')),
                ('description', ckeditor.fields.RichTextField()),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Image', upload_to='staticfiles/uploads/event/', verbose_name='Image')),
                ('start_time', models.DateTimeField(null=True)),
                ('modefied_time', models.DateTimeField(null=True)),
                ('category_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='go.category', verbose_name='Categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
