# Generated by Django 3.2.9 on 2021-12-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
