# Generated by Django 3.2.9 on 2021-12-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0003_alter_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(help_text='event type', max_length=500, null=True, unique=True, verbose_name='type'),
        ),
    ]
