# Generated by Django 3.2.9 on 2021-12-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0004_events_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='modefied_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(help_text='please write title', max_length=500, null=True, verbose_name='title'),
        ),
    ]
