# Generated by Django 3.2.9 on 2021-12-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0006_alter_events_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
