# Generated by Django 3.2.9 on 2021-12-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0007_alter_events_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
