# Generated by Django 3.2.9 on 2021-12-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0008_events_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
