# Generated by Django 3.2.9 on 2021-12-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0010_follow_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='organizer',
            field=models.ManyToManyField(related_name='organizer', to='go.Profile'),
        ),
    ]
