# Generated by Django 3.2.9 on 2021-12-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0012_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
